// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: esp32Rasberry

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void wifiSetUp(lv_event_t * e);
void connectToWiFi(lv_event_t * e);
void WiFiReFresh(lv_event_t * e);
void changeScrBrit(lv_event_t * e);
void RebootNow(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
