// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: esp32Rasberry

#include "ui.h"

#include "main.h"
String WifyNames[100];
String WifyName;
void RebootNow(lv_event_t *e)
{
	ESP.restart();
}

void changeScrBrit(lv_event_t *e)
{
	ledcSetup(0, 300, 8);
	ledcAttachPin(TFT_BL, 0);
	ledcWrite(0, lv_slider_get_value(ui_britnes)); /* Screen brightness can be modified by adjusting this parameter. (0-255) */
}

void wifiSetUp(lv_event_t *e)
{
	yield();
	network_Nubers = WiFi.scanNetworks();
	yield();
	for (int i = 0; i < network_Nubers; i++)
	{
		WifyNames[i] = WiFi.SSID(i);
		WifyName += WiFi.SSID(i);
		if (i != network_Nubers)
			WifyName += "\n";
	}
	lv_roller_set_options(ui_Roller1, WifyName.c_str(), LV_ROLLER_MODE_NORMAL);
}
